spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    com.example.urlshortener: INFO

management:
  tracing.sampling.probability: ${TRACING_SAMPLE_RATE:0.1}